name: CI/CD test workflow

on:
  push:
    branches: [ feat/convert-multi-module ]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: set up jdk 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.8

      - name: give authority
        run: chmod +x gradlew

      - name: build
        run: ./gradlew brtrip-api:build